/* ================================================================ */
/* 1. TABLAS BASE DEL BANCO (CORE)                                 */
/* ================================================================ */
-- 1. Limpieza (En orden inverso de dependencia)
DROP VIEW IF EXISTS V_INV_CUENTAS_CLIENTE;
DROP TABLE IF EXISTS INV_SOLICITUD;
DROP TABLE IF EXISTS CUENTA_AHORROS;
DROP TABLE IF EXISTS CUENTA_CORRIENTE;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS INV_PRODUCTO;


CREATE TABLE USUARIOS (
    ID_USUARIO SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CEDULA VARCHAR(10) UNIQUE NOT NULL,
    NOMBRE_COMPLETO VARCHAR(100)
);

CREATE TABLE CUENTA_AHORROS (
    ID_CUENTA SERIAL PRIMARY KEY,
    N_CUENTA VARCHAR(20) UNIQUE NOT NULL,
    ID_USUARIO INT REFERENCES USUARIOS(ID_USUARIO), 
    SALDO_ACTUAL DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE CUENTA_CORRIENTE (
    ID_CUENTA SERIAL PRIMARY KEY,
    N_CUENTA VARCHAR(20) UNIQUE NOT NULL,
    ID_USUARIO INT REFERENCES USUARIOS(ID_USUARIO),
    SALDO_ACTUAL DECIMAL(12,2) DEFAULT 0
);

/* ================================================================ */
/* 2. VISTA AUXILIAR: UNIFICA EL ORIGEN DE FONDOS                  */
/* ================================================================ */

CREATE OR REPLACE VIEW V_INV_CUENTAS_CLIENTE AS
SELECT 'AHORRO' AS TIPO_ORIGEN, ID_CUENTA AS ID_INTERNO, N_CUENTA AS NUMERO_CUENTA, ID_USUARIO AS ID_CLIENTE, SALDO_ACTUAL
FROM CUENTA_AHORROS
UNION ALL
SELECT 'CORRIENTE' AS TIPO_ORIGEN, ID_CUENTA AS ID_INTERNO, N_CUENTA AS NUMERO_CUENTA, ID_USUARIO AS ID_CLIENTE, SALDO_ACTUAL
FROM CUENTA_CORRIENTE;

/* ================================================================ */
/* 3. MODULO DE INVERSIONES (INV_)                                 */
/* ================================================================ */

CREATE TABLE INV_PRODUCTO (
    ID_PRODUCTO     SERIAL PRIMARY KEY,
    CODIGO          VARCHAR(20) NOT NULL UNIQUE,
    NOMBRE          VARCHAR(50) NOT NULL,
    TASA_ANUAL      DECIMAL(5,2) NOT NULL,
    MONTO_MIN       DECIMAL(12,2) NOT NULL,
    PLAZO_MIN_DIAS  INT NOT NULL,
    ES_FLEXIBLE     BOOLEAN DEFAULT FALSE
);

CREATE TABLE INV_SOLICITUD (
    ID_INVERSION    SERIAL PRIMARY KEY,
    ID_CLIENTE      INT REFERENCES USUARIOS(ID_USUARIO), -- Conectado al Login
    ID_PRODUCTO     INT REFERENCES INV_PRODUCTO(ID_PRODUCTO),
    ORIGEN_FONDOS   VARCHAR(20) NOT NULL,
    ID_CUENTA_ORIGEN INT NOT NULL,
    MONTO_CAPITAL   DECIMAL(12,2) NOT NULL,
    FECHA_INICIO    DATE DEFAULT CURRENT_DATE,
    FECHA_FIN       DATE NOT NULL,
    ESTADO          VARCHAR(20) DEFAULT 'ACTIVA',
    INTERES_GANADO  DECIMAL(12,2) DEFAULT 0,
    TOTAL_A_RECIBIR DECIMAL(12,2) DEFAULT 0
);

-- (Aquí incluirías INV_MOVIMIENTO_FINANCIERO e INV_PENALIZACION igual que antes)

/* ================================================================ */
/* 4. DATOS DE PRUEBA (DATA SEEDING)                               */
/* ================================================================ */

-- Contraseña: pichincha123 (Hash generado para pruebas)
INSERT INTO USUARIOS (USERNAME, PASSWORD_HASH, CEDULA, NOMBRE_COMPLETO) 
VALUES ('estudiante_espe', 'pbkdf2:sha256:260000$vY8v7hG2$c7...', '1712345678', 'Usuario de Pruebas');

INSERT INTO CUENTA_AHORROS (N_CUENTA, ID_USUARIO, SALDO_ACTUAL) VALUES ('2201456789', 1, 2500.00);

INSERT INTO INV_PRODUCTO (CODIGO, NOMBRE, TASA_ANUAL, MONTO_MIN, PLAZO_MIN_DIAS, ES_FLEXIBLE) VALUES 
('PLAZODOLAR', 'Inversión Plazo Dólar', 6.50, 500.00, 30, FALSE),
('ARMADOLAR', 'Ahorro Programado ArmaDólar', 5.00, 50.00, 180, TRUE);